services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001":"5000"
    volumes:
      - ./backend/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root